# Generated by Django 5.0.1 on 2025-01-27 23:11

import django.db.models.deletion
import django.utils.timezone
import mainwebsite.extras
import mainwebsite.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id_almacen', models.AutoField(primary_key=True, serialize=False)),
                ('creado_en', models.DateField(auto_now_add=True)),
                ('nombre_almacen', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('nota', models.TextField(blank=True, default='', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('creado_en', models.DateField(auto_now_add=True)),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('direccion', models.TextField(blank=True)),
                ('correo', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('telefono', models.CharField(max_length=12, null=True)),
                ('telefono2', models.CharField(blank=True, max_length=12, null=True)),
                ('rif', models.CharField(max_length=15)),
                ('cliente_image', models.ImageField(blank=True, default='', upload_to=mainwebsite.extras.generar_nombre_imgen_cliente)),
            ],
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id_destino', models.AutoField(primary_key=True, serialize=False)),
                ('creado_en', models.DateField(auto_now_add=True)),
                ('nombre_destino', models.CharField(max_length=200)),
                ('ciudad', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('creado_en', models.DateField(auto_now_add=True)),
                ('cod_producto', models.CharField(blank=True, max_length=20)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('descripcion_prod', models.TextField(blank=True)),
                ('cant_min', models.PositiveIntegerField(default=0)),
                ('cant_max', models.PositiveIntegerField(default=0)),
                ('prod_image', models.ImageField(blank=True, default='', upload_to=mainwebsite.extras.generar_nombre_imgen_producto)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('creado_en', models.DateField(auto_now_add=True)),
                ('nombre_proveedor', models.CharField(max_length=200)),
                ('correo', models.CharField(blank=True, max_length=150)),
                ('tlf_proveedor', models.CharField(blank=True, max_length=12, null=True)),
                ('nota_proveedor', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login', 'Inicio de Sesión'), ('logout', 'Cerrar sesión'), ('failed_attempt', 'Intento Fallido')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(max_length=255)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('operating_system', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Acceso',
                'verbose_name_plural': 'Historial de accesos',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('creado_en', models.DateField(auto_now_add=True)),
                ('num_orden', models.IntegerField()),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(max_length=20)),
                ('num_factura', models.CharField(max_length=20)),
                ('desc_requisicion', models.CharField(max_length=20)),
                ('fecha_requisicion', models.DateField(blank=True, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('solicitado', models.CharField(max_length=25)),
                ('tlf_solicitado', models.CharField(blank=True, max_length=12, null=True)),
                ('fecha_ult_mod', models.DateField(auto_now_add=True)),
                ('num_lote', models.CharField(max_length=20)),
                ('id_cliente', models.ForeignKey(default=mainwebsite.models.Cliente.get_default_pk, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainwebsite.cliente')),
                ('id_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainwebsite.destino')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orden_Producto',
            fields=[
                ('id_orden_prod', models.AutoField(primary_key=True, serialize=False)),
                ('creado_en', models.DateField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
                ('precio_unit', models.DecimalField(decimal_places=3, default=0.0, max_digits=9)),
                ('empaque', models.CharField(max_length=20)),
                ('id_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainwebsite.orden')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainwebsite.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('creado_en', models.DateField(auto_now_add=True)),
                ('precio_unit_ref', models.DecimalField(decimal_places=3, max_digits=9)),
                ('cant_disponible', models.IntegerField(default=0)),
                ('fecha_ult_mod_inv', models.DateField(default=django.utils.timezone.now)),
                ('nota', models.TextField(blank=True)),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('DEVOLUCION', 'Devolución'), ('AJUSTE', 'Ajuste')], default='ENTRADA', max_length=20)),
                ('id_almacen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainwebsite.almacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainwebsite.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, max_length=200, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('telefono2', models.CharField(blank=True, max_length=12, null=True)),
                ('cedula', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('estado', models.CharField(blank=True, max_length=40, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('cargo', models.CharField(blank=True, max_length=200, null=True)),
                ('tema_sistema', models.CharField(choices=[('red', 'Rojo'), ('blue', 'Azul'), ('grey', 'Gris'), ('lime', 'Lima'), ('pink', 'Rosado'), ('brown', 'Marrón')], default='red', max_length=20)),
                ('image', models.ImageField(blank=True, default='', upload_to=mainwebsite.extras.generar_nombre_imgen_usuario)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='id_proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainwebsite.proveedor'),
        ),
        migrations.CreateModel(
            name='Registro_inventario',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('desc_accion', models.CharField(max_length=150)),
                ('tipo_accion', models.CharField(max_length=150)),
                ('fecha_accion', models.DateField(auto_now_add=True)),
                ('cantidad_accion', models.PositiveIntegerField()),
                ('id_inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainwebsite.inventario')),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('device', models.CharField(max_length=255)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('C', 'Creación'), ('U', 'Actualización'), ('D', 'Eliminación')], default='', max_length=1)),
                ('changes', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.JSONField(default=dict)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='mainwebsite_content_9d49a5_idx'), models.Index(fields=['timestamp'], name='mainwebsite_timesta_ff1233_idx')],
            },
        ),
        migrations.CreateModel(
            name='Prod_Dest',
            fields=[
                ('id_prod_dest', models.AutoField(primary_key=True, serialize=False)),
                ('creado_en', models.DateField(auto_now_add=True)),
                ('consumo_prom_dia', models.DecimalField(decimal_places=2, max_digits=9)),
                ('fecha_ult_sumin', models.DateField()),
                ('id_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainwebsite.destino')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainwebsite.producto')),
            ],
            options={
                'unique_together': {('id_destino', 'id_producto')},
            },
        ),
    ]
