# Generated by Django 4.2.5 on 2023-10-19 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0006_alter_orden_producto_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden_producto',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainwebsite.producto'),
        ),
    ]
