# Generated by Django 4.2.5 on 2023-10-19 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0007_alter_orden_producto_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='id_almacen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainwebsite.almacen'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainwebsite.producto'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='id_cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainwebsite.cliente'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='id_destino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainwebsite.destino'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainwebsite.proveedor'),
        ),
    ]
