# Generated by Django 4.2.5 on 2023-10-19 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0008_alter_inventario_id_almacen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='cant_disponible',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cant_max',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cant_min',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha_ult_mod_inv',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
