# Generated by Django 4.2.5 on 2023-10-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0010_remove_registro_inventario_creado_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro_inventario',
            old_name='cantidad',
            new_name='cantidad_accion',
        ),
        migrations.AddField(
            model_name='inventario',
            name='cant_inicial',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
