# Generated by Django 4.2.5 on 2023-10-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0012_remove_inventario_cant_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='cant_disponible',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
