# Generated by Django 4.2.5 on 2023-10-22 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0015_alter_prod_dest_consumo_prom_dia'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prod_dest',
            unique_together={('id_destino', 'id_producto')},
        ),
    ]
