# Generated by Django 5.0.1 on 2024-09-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0020_alter_producto_cod_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='prod_image',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
    ]
