# Generated by Django 5.0.1 on 2025-01-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0022_cliente_correo_cliente_telefono2'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='prod_image',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
    ]
