# Generated by Django 5.0.1 on 2025-01-04 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0023_cliente_prod_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='prod_image',
            new_name='cliente_image',
        ),
    ]
