# Generated by Django 5.0.1 on 2025-01-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0025_almacen_direccion_almacen_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='num_factura',
            field=models.CharField(max_length=20),
        ),
    ]
