# Generated by Django 5.0.1 on 2025-01-12 22:36

import django.db.models.deletion
import mainwebsite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0026_alter_orden_num_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rif',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='id_cliente',
            field=models.ForeignKey(default=mainwebsite.models.Cliente.get_default_pk, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainwebsite.cliente'),
        ),
    ]
