# Generated by Django 5.0.1 on 2025-01-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0029_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cliente_image',
            field=models.ImageField(blank=True, default='', upload_to='images/clients'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prod_image',
            field=models.ImageField(blank=True, default='', upload_to='images/products'),
        ),
    ]
