# Generated by Django 5.0.1 on 2025-01-21 21:14

import mainwebsite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0030_alter_cliente_cliente_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tema_sistema',
            field=models.CharField(choices=[('red', 'Rojo'), ('blue', 'Azul'), ('grey', 'Gris'), ('lime', 'Lima'), ('pink', 'Rosado'), ('brown', 'Marrón')], default='red', max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente_image',
            field=models.ImageField(blank=True, default='', upload_to=mainwebsite.models.generar_nombre_imgen_cliente),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prod_image',
            field=models.ImageField(blank=True, default='', upload_to=mainwebsite.models.generar_nombre_imgen_producto),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=mainwebsite.models.generar_nombre_imgen_usuario),
        ),
    ]
