# Generated by Django 4.2.5 on 2023-09-18 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0002_alter_almacen_id_almacen_alter_cliente_id_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='cod_producto',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='descripcion_prod',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='nota',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='correo',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nota_proveedor',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tlf_proveedor',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('creado_en', models.DateField(auto_now_add=True)),
                ('num_orden', models.IntegerField()),
                ('fecha_emision', models.DateField()),
                ('estado', models.CharField(max_length=20)),
                ('num_factura', models.CharField(max_length=40)),
                ('desc_requisicion', models.CharField(max_length=20)),
                ('fecha_requisicion', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('solicitado', models.CharField(max_length=25)),
                ('tlf_solicitado', models.CharField(max_length=12)),
                ('fecha_ult_mod', models.DateField()),
                ('num_lote', models.CharField(max_length=20)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainwebsite.cliente')),
                ('id_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainwebsite.destino')),
                ('id_producto', models.ManyToManyField(through='mainwebsite.Orden_Prod', to='mainwebsite.inventario')),
            ],
        ),
        migrations.AlterField(
            model_name='orden_prod',
            name='id_orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainwebsite.orden'),
        ),
        migrations.DeleteModel(
            name='Ordenes',
        ),
    ]
