# Generated by Django 4.2.5 on 2023-09-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0003_alter_inventario_cod_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rif',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
