# Generated by Django 4.2.5 on 2023-09-18 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainwebsite', '0004_alter_cliente_direccion_alter_cliente_rif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='id_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
