# Generated by Django 4.2.5 on 2023-10-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0005_orden_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fecha_entrega',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='fecha_requisicion',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='fecha_ult_mod',
            field=models.DateField(auto_now_add=True),
        ),
    ]
