# Generated by Django 4.2.5 on 2023-10-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0008_rename_orden_prod_orden_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden_producto',
            name='precio_unit',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=9),
        ),
    ]
