# Generated by Django 4.2.5 on 2023-10-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0009_alter_inventario_cant_disponible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro_inventario',
            name='creado_en',
        ),
        migrations.AlterField(
            model_name='registro_inventario',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
    ]
