# Generated by Django 4.2.5 on 2023-10-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0011_rename_cantidad_registro_inventario_cantidad_accion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='cant_max',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='cant_min',
        ),
        migrations.AddField(
            model_name='producto',
            name='cant_max',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='cant_min',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
