# Generated by Django 4.2.5 on 2023-10-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0014_alter_cliente_telefono_alter_orden_tlf_solicitado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod_dest',
            name='consumo_prom_dia',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
