# Generated by Django 5.0.1 on 2024-09-28 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0016_alter_prod_dest_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='prod_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
