# Generated by Django 5.0.1 on 2024-09-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0017_producto_prod_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='prod_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
