# Generated by Django 5.0.1 on 2024-09-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0019_alter_producto_prod_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cod_producto',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
