# Generated by Django 5.0.1 on 2025-01-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0024_rename_prod_image_cliente_cliente_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='almacen',
            name='nota',
            field=models.TextField(blank=True, default='', max_length=20, null=True),
        ),
    ]
